#! /bin/sh

MY_SCRIPTS=$HOME/.config/bspwm/scripts

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/eww/bar/launch_bar
$MY_SCRIPTS/eww_fullscreen

pgrep -x picom > /dev/null || picom --config $HOME/.config/picom/picom.conf &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config border_width	2
bspc config window_gap		2
bspc config -m eDP-1 top_padding    30

bspc config split_ratio		0.50
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Nm-connection-editor state=floating follow=on
bspc rule -a Mousepad state=floating follow=on
bspc rule -a Emacs state=tiled follow=on
bspc rule -a jetbrains-idea-ce state=floating follow=on

feh --no-fehbg --bg-fill $HOME/.config/bspwm/wallpapers/snow_mountain.jpg

pgrep -x thunar > /dev/null || thunar --daemon &
pgrep -x flameshot > /dev/null || flameshot &
#pgrep -x emacs > /dev/null || emacs --daemon &

wmname LG3D
