#!/bin/bash

LAUNCH_BAR="$HOME/.config/eww/bar/launch_bar"

bspc subscribe node_state | while read -r _ _ _ _ state flag; do
    if [ "$state" != "fullscreen" ]; then
        continue
    fi
    if [ "$flag" == on ]; then
        ${LAUNCH_BAR} close
    else
        ${LAUNCH_BAR} open
    fi
done &
