#!/bin/bash

MONITORS=($(xrandr -q | rg -w connected | awk '{ print $1 }'))
NUM_MONITORS=$(xrandr -q | rg -w connected | wc -l)

if [[ $NUM_MONITORS == 1 ]]; then
    echo $MONITORS
    xrandr --output "$MONITORS" --primary --mode 1920x1080 --rate 48.01
    echo "reconfig workspace"
    bspc monitor "$MONITORS" -d 1 2 3 4 5 6 7 8 9
    echo "reload backgroud"
    DIS_MON=($(xrandr -q | rg -w disconnected | awk '{ print $1 }'))
    xrandr --output "$DIS_MON" --off
    feh --no-fehbg --bg-fill $HOME/.config/bspwm/wallpapers/snow_mountain.jpg
    echo "1 monitors setting!"
elif [[ $NUM_MONITORS == 2 ]]; then
    MONITOR1=${MONITORS[0]}
    MONITOR2=${MONITORS[1]}
    echo $MONITOR1
    echo $MONITOR2
    #xrandr -q
    #echo "Enter resolution: "
    #read resolution
    echo "setting second monitor"
    CMD="xrandr --output $MONITOR1 --primary --mode 1920x1080 --rate 48.01 --output $MONITOR2 --auto --right-of $MONITOR1"
    echo $CMD
    bash -c "$CMD"
    echo "reconfig workspace"
    bspc monitor "$MONITOR1" -d 1 2 3 4 5
    bspc monitor "$MONITOR2" -d 6 7 8 9
    echo "reload backgroud"
    feh --no-fehbg --bg-fill $HOME/.config/bspwm/wallpapers/snow_mountain.jpg
    echo "2 monitors settings"
else
    echo "3 monitors doesn't have an implementation!"
fi
