#!/bin/bash

AUDIO_STATUS=$(amixer get Master | rg 'Front Left:' | awk -F '[][]+' '{ print $4 }')


if [[ $AUDIO_STATUS == "on" ]]; then
    echo 󰕾
elif [[ $AUDIO_STATUS == "off" ]]; then
    echo 󰖁
fi

