#!/bin/bash

calendar() {
LOCK_FILE="$HOME/.cache/eww-calendar.lock"
EWW_BIN="$HOME/.local/bin/eww"

run() {
    ${EWW_BIN} -c $HOME/.config/eww/bar open calendar
}

# Open widgets
if [[ ! -f "$LOCK_FILE" ]]; then
    ${EWW_BIN} -c $HOME/.config/eww/bar close system audio_ctl
    touch "$LOCK_FILE"
    run && echo "ok good!"
else
    ${EWW_BIN} -c $HOME/.config/eww/bar close calendar
    rm "$LOCK_FILE" && echo "closed"
fi
}


system() {
LOCK_FILE_MEM="$HOME/.cache/eww-system.lock"
EWW_BIN="$HOME/.local/bin/eww"

run() {
    ${EWW_BIN} -c $HOME/.config/eww/bar open system 
}

# Open widgets
if [[ ! -f "$LOCK_FILE_MEM" ]]; then
    ${EWW_BIN} -c $HOME/.config/eww/bar close calendar audio_ctl
    touch "$LOCK_FILE_MEM"
    run && echo "ok good!"
else
    ${EWW_BIN} -c $HOME/.config/eww/bar close system 
    rm "$LOCK_FILE_MEM" && echo "closed"
fi
}


audio() {
LOCK_FILE_AUDIO="$HOME/.cache/eww-audio.lock"
EWW_BIN="$HOME/.local/bin/eww"

run() {
    ${EWW_BIN} -c $HOME/.config/eww/bar open audio_ctl 
}

# Open widgets
if [[ ! -f "$LOCK_FILE_AUDIO" ]]; then
    ${EWW_BIN} -c $HOME/.config/eww/bar close system calendar 
    touch "$LOCK_FILE_AUDIO"
    run && echo "ok good!"
else
    ${EWW_BIN} -c $HOME/.config/eww/bar close audio_ctl
    rm "$LOCK_FILE_AUDIO" && echo "closed"
fi
}

close() {
    LOCK_FILE="$HOME/.cache/eww-calendar.lock"
    LOCK_FILE_MEM="$HOME/.cache/eww-system.lock"
    LOCK_FILE_AUDIO="$HOME/.cache/eww-audio.lock"
    EWW_BIN="$HOME/.local/bin/eww"
    ${EWW_BIN} -c $HOME/.config/eww/bar close system calendar audio_ctl
    rm "$LOCK_FILE" "$LOCK_FILE_MEM" "$LOCK_FILE_AUDIO" && echo "closed"
}


if [ "$1" = "calendar" ]; then
calendar
elif [ "$1" = "system" ]; then
system
elif [ "$1" = "audio" ]; then
audio
elif [ "$1" = "close" ]; then
close
fi
