#!/bin/bash

status=$(nmcli g | rg -oe "disconnected")
essid=$(nmcli c | rg wlan0 | awk '{print ($1)}')
signal=$(nmcli d wifi list | rg '\*' | awk '{ print $8 }')

if [ $status ] ; then
    icon="󰇨"
    text=""
    col="#575268"

else
    icon=""
    text="${essid} ${signal}%"
    col="#a1bdce"
fi


if [[ "$1" == "--COL" ]]; then
    echo $col	
elif [[ "$1" == "--ESSID" ]]; then
	echo $text
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
fi

